In [2]:
import numpy as np
import matplotlib.pyplot as plt
import cv2

def _imshow(img):
    cv2.imshow('image', img)
    plt.show()
    # specify a wait key from keyboard
    k = cv2.waitKey(0) & 0xFF

    if k == 27: #esc in keyboard
        cv2.destroyAllWindows() #close the window   

    elif k == ord('s'): #if order is s save the image
        cv2.imwrite('lena_copy.png', img) #write image in your pc     
        cv2.destroyAllWindows() # close the window 


img = cv2.imread("lena_copy.png")

imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret, thresh = cv2.threshold(imgray, 127, 255, 0)

contours, hierarchy = cv2.findContours(thresh, cv2.RETR_LIST     , cv2.CHAIN_APPROX_SIMPLE)

print("Number of contours = " + str(len(contours)))

print(contours[0])



cv2.drawContours(img, contours, -1, (0, 255, 0), 3)

cv2.drawContours(imgray, contours, -1, (0, 255, 0), 3)

_imshow(img)


# cv2.imshow('Image', img)

# cv2.imshow('Image GRAY', imgray)

# cv2.waitKey(0)

# cv2.destroyAllWindows()#close window

Number of contours = 120
[[[3536 1329]]

 [[3536 1389]]

 [[3726 1389]]

 [[3727 1390]]

 [[3856 1390]]

 [[3856 1332]]

 [[3855 1331]]

 [[3855 1330]]

 [[3673 1330]]

 [[3672 1329]]]
